# _config.yml
title: Watch-Doggo
description: Open-source service monitor
theme: jekyll-theme-cayman
baseurl: /watch-doggo
url: https://zyra-engineering-ltda.github.io
include:
  - _includes/head-custom.html