name: release-please
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: watch-doggo
          bump-minor-pre-major: true
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"refactor","section":"Refactors","hidden":true},
              {"type":"docs","section":"Docs","hidden":true},
              {"type":"chore","section":"Chores","hidden":true},
              {"type":"test","section":"Tests","hidden":true}
            ]
